/* Modules/MoreGP/ExtraGPs.sql */
  INSERT INTO Language_en_US
    (Tag, Text)
  VALUES
  --
  --          G.Musicians
  --
    ('TXT_KEY_GREAT_PERSON_M__010', 'Manuel De Sumaya'),
    ('TXT_KEY_GREAT_PERSON_M__020', 'Agbani Nguru Ikorodo Group'),
    ('TXT_KEY_GREAT_PERSON_M__030', 'Hammamizade Ismail Dede Efendi'),
    ('TXT_KEY_GREAT_PERSON_M__040', 'Robert Herrick'),
    ('TXT_KEY_GREAT_PERSON_M__050', 'Gaetano Donizetti'),
    ('TXT_KEY_GREAT_PERSON_M__060', 'George Linley'),
    ('TXT_KEY_GREAT_PERSON_M__070', 'Stephen Foster'),
    ('TXT_KEY_GREAT_PERSON_M__080', 'William Vincent Wallace'),
    ('TXT_KEY_GREAT_PERSON_M__090', 'Gabriel Faure'),
    ('TXT_KEY_GREAT_PERSON_M__100', 'Josephine Baker'),
    ('TXT_KEY_GREAT_PERSON_M__110', 'Mohamed El Qasabgi'),
    ('TXT_KEY_GREAT_PERSON_M__120', 'Carl Orff'),
    ('TXT_KEY_GREAT_PERSON_M__130', 'Django Reinhardt'),
    ('TXT_KEY_GREAT_PERSON_M__140', 'Mahmoud Zolfonoun'),
    ('TXT_KEY_GREAT_PERSON_M__150', 'Edith Piaf'),
    ('TXT_KEY_GREAT_PERSON_M__160', 'Luis Alberti'),
    ('TXT_KEY_GREAT_PERSON_M__170', 'Glenn Miller'),
    ('TXT_KEY_GREAT_PERSON_M__180', 'Thelonious Monk'),
    ('TXT_KEY_GREAT_PERSON_M__190', 'Ajim Krajka'),
    ('TXT_KEY_GREAT_PERSON_M__200', 'Ray Barretto'),
    ('TXT_KEY_GREAT_PERSON_M__210', 'The Beattles'),
    ('TXT_KEY_GREAT_PERSON_M__220', 'Dr. M. Balamuralikrishna'),
    ('TXT_KEY_GREAT_PERSON_M__230', 'Janis Joplin'),
    ('TXT_KEY_GREAT_PERSON_M__240', 'David Bowie'),
    ('TXT_KEY_GREAT_PERSON_M__250', 'The Temprtations'),
    ('TXT_KEY_GREAT_PERSON_M__260', 'Fela Anikylapo Kuti'),
    ('TXT_KEY_GREAT_PERSON_M__270', 'Franco Du Congo'),
    ('TXT_KEY_GREAT_PERSON_M__280', 'Ram Jam'),
    ('TXT_KEY_GREAT_PERSON_M__290', 'Ricky Lee Jones'),
    ('TXT_KEY_GREAT_PERSON_M__300', 'Horace Andy'),
    ('TXT_KEY_GREAT_PERSON_M__310', 'Womack and Womack'),
    ('TXT_KEY_GREAT_PERSON_M__320', 'Ernst Reijseger'),
    ('TXT_KEY_GREAT_PERSON_M__330', 'Sinead O Connor'),
    ('TXT_KEY_GREAT_PERSON_M__340', 'The Sugar Hill Gang'),
    ('TXT_KEY_GREAT_PERSON_M__350', 'Karl Jenkins'),
    ('TXT_KEY_GREAT_PERSON_M__360', 'Ruben Gonzalez'),
    ('TXT_KEY_GREAT_PERSON_M__370', 'UFO'),
    ('TXT_KEY_GREAT_PERSON_M__380', 'Shigeru Umebayashi'),
    ('TXT_KEY_GREAT_PERSON_M__390', 'Degung Sunda'),
    ('TXT_KEY_GREAT_PERSON_M__400', 'Sawai Hikaru'),
    ('TXT_KEY_GREAT_PERSON_M__410', 'Peaches and Iggy Pop'),
    ('TXT_KEY_GREAT_PERSON_M__420', 'Roberto Fonseca'),
    ('TXT_KEY_GREAT_PERSON_M__430', 'Nils Frahm'),
    ('TXT_KEY_GREAT_PERSON_M__440', 'Chad Lawson'),
    ('TXT_KEY_GREAT_PERSON_M__450', 'Balti'),
    ('TXT_KEY_GREAT_PERSON_M__460', 'Luis Fonsi'),
    ('TXT_KEY_GREAT_PERSON_M__470', 'Mannat Noor'),
    ('TXT_KEY_GREAT_PERSON_M__480', 'Chilly Gonzales'),
    ('TXT_KEY_GREAT_PERSON_M__490', 'The Weeknd'),
    ('TXT_KEY_GREAT_PERSON_M__500', 'Gabriel Garzon Montano'),
  --	
    ('TXT_KEY_GREAT_WORK_MW_010', 'Hieremiae Prophetae Lamentationes'),
    ('TXT_KEY_GREAT_WORK_MW_020', 'Ije Nwayo'),
    ('TXT_KEY_GREAT_WORK_MW_030', 'Ey But I Nev Eda Olmusum_Muptela'),
    ('TXT_KEY_GREAT_WORK_MW_040', 'Cherry Ripe'),
    ('TXT_KEY_GREAT_WORK_MW_050', 'Lucia Di Lammermoor'),
    ('TXT_KEY_GREAT_WORK_MW_060', 'I''ve Left The Snow Clad Hills'),
    ('TXT_KEY_GREAT_WORK_MW_070', 'Gwine To Run All Night'),
    ('TXT_KEY_GREAT_WORK_MW_080', 'Lurline'),
    ('TXT_KEY_GREAT_WORK_MW_090', 'Requiem'),
    ('TXT_KEY_GREAT_WORK_MW_100', 'Blue Skies'),
    ('TXT_KEY_GREAT_WORK_MW_110', 'Zibrayati'),
    ('TXT_KEY_GREAT_WORK_MW_120', 'Carmina Burana'),
    ('TXT_KEY_GREAT_WORK_MW_130', 'My Serenade'),
    ('TXT_KEY_GREAT_WORK_MW_140', 'Rooh Afza'),
    ('TXT_KEY_GREAT_WORK_MW_150', 'La Vie En Rose'),
    ('TXT_KEY_GREAT_WORK_MW_160', 'Dame El Si'),
    ('TXT_KEY_GREAT_WORK_MW_170', 'In The Mood'),
    ('TXT_KEY_GREAT_WORK_MW_180', 'Misterioso'),
    ('TXT_KEY_GREAT_WORK_MW_190', 'Fantazi'),
    ('TXT_KEY_GREAT_WORK_MW_200', 'Guajira y Tambo'),
    ('TXT_KEY_GREAT_WORK_MW_210', 'Help'),
    ('TXT_KEY_GREAT_WORK_MW_220', 'Endaro Mahanubhavulu'),
    ('TXT_KEY_GREAT_WORK_MW_230', 'Summertime'),
    ('TXT_KEY_GREAT_WORK_MW_240', 'Life On Mars'),
    ('TXT_KEY_GREAT_WORK_MW_250', 'Papa was a Rolling Stone'),
    ('TXT_KEY_GREAT_WORK_MW_260', 'Water No Get Enemy'),
    ('TXT_KEY_GREAT_WORK_MW_270', 'Liberte'),
    ('TXT_KEY_GREAT_WORK_MW_280', 'Black Betty'),
    ('TXT_KEY_GREAT_WORK_MW_290', 'Chuck Es In Love'),
    ('TXT_KEY_GREAT_WORK_MW_300', 'It''s gonna be dread'),
    ('TXT_KEY_GREAT_WORK_MW_310', 'Teardrops'),
    ('TXT_KEY_GREAT_WORK_MW_320', 'Shadow'),
    ('TXT_KEY_GREAT_WORK_MW_330', 'Dont''t cry for me Argentina'),
    ('TXT_KEY_GREAT_WORK_MW_340', 'Rapper''s Delight'),
    ('TXT_KEY_GREAT_WORK_MW_350', 'Palladio'),
    ('TXT_KEY_GREAT_WORK_MW_360', 'Almendra'),
    ('TXT_KEY_GREAT_WORK_MW_370', 'Loud Minority'),
    ('TXT_KEY_GREAT_WORK_MW_380', 'In The Mood For Love'),
    ('TXT_KEY_GREAT_WORK_MW_390', 'Menyejukkan Hati'),
    ('TXT_KEY_GREAT_WORK_MW_400', 'Esoragoto'),
    ('TXT_KEY_GREAT_WORK_MW_410', 'Kick it'),
    ('TXT_KEY_GREAT_WORK_MW_420', 'Drume Negrita'),
    ('TXT_KEY_GREAT_WORK_MW_430', 'me'),
    ('TXT_KEY_GREAT_WORK_MW_440', 'Nocturne in F minor'),
    ('TXT_KEY_GREAT_WORK_MW_450', 'Ya Lili'),
    ('TXT_KEY_GREAT_WORK_MW_460', 'Despacito'),
    ('TXT_KEY_GREAT_WORK_MW_470', 'Laung Laachi'),
    ('TXT_KEY_GREAT_WORK_MW_480', 'Nimbus'),
    ('TXT_KEY_GREAT_WORK_MW_490', 'Blinding Lights'),
    ('TXT_KEY_GREAT_WORK_MW_500', 'Bloom');

  INSERT INTO Language_en_US
    (Tag, Text)
  VALUES
  --
  --          G.Artists
  --
    ('TXT_KEY_GREAT_PERSON_A__010', 'Yan Liben'),
    ('TXT_KEY_GREAT_PERSON_A__020', 'Tepantitla'),
    ('TXT_KEY_GREAT_PERSON_A__030', 'Zhang Zeduan'),
    ('TXT_KEY_GREAT_PERSON_A__040', 'Kano Motonobu'),
    ('TXT_KEY_GREAT_PERSON_A__050', 'Mogyeondo'),
    ('TXT_KEY_GREAT_PERSON_A__060', 'Judith Leyster'),
    ('TXT_KEY_GREAT_PERSON_A__070', 'Jeong Seon'),
    ('TXT_KEY_GREAT_PERSON_A__080', 'Samuel Felsted'),
    ('TXT_KEY_GREAT_PERSON_A__090', 'Hyewon'),
    ('TXT_KEY_GREAT_PERSON_A__092', 'Thomas Cole'),
    ('TXT_KEY_GREAT_PERSON_A__095', 'Johan Christian Dahl'),
    ('TXT_KEY_GREAT_PERSON_A__100', 'Raden Saleh'),
    ('TXT_KEY_GREAT_PERSON_A__110', 'Jan Matejko'),
    ('TXT_KEY_GREAT_PERSON_A__115', 'Albert Bierstadt'),
    ('TXT_KEY_GREAT_PERSON_A__120', 'Edouard Detaille'),
    ('TXT_KEY_GREAT_PERSON_A__130', 'Berthold Woltze'),
    ('TXT_KEY_GREAT_PERSON_A__135', 'Ivan Aivazovsky'),
    ('TXT_KEY_GREAT_PERSON_A__140', 'John Atkinson Grimshaw'),
    ('TXT_KEY_GREAT_PERSON_A__150', 'Black Hawk'),
    ('TXT_KEY_GREAT_PERSON_A__155', 'Albert Lynch'),
    ('TXT_KEY_GREAT_PERSON_A__160', 'Princess Ka''iulani'),
    ('TXT_KEY_GREAT_PERSON_A__170', 'Akseli Gallen Kallela'),
    ('TXT_KEY_GREAT_PERSON_A__178', 'Vladimir Baranov-Rossine'),
    ('TXT_KEY_GREAT_PERSON_A__180', 'Frantisek Kupka'),
    ('TXT_KEY_GREAT_PERSON_A__185', 'Ludwig Meidner'),
    ('TXT_KEY_GREAT_PERSON_A__187', 'Alexander Yuriyevich'),
    ('TXT_KEY_GREAT_PERSON_A__190', 'Wojciech Kossak'),
    ('TXT_KEY_GREAT_PERSON_A__193', 'Alphonse Mucha'),
    ('TXT_KEY_GREAT_PERSON_A__194', 'William Paxton'),
    ('TXT_KEY_GREAT_PERSON_A__195', 'Piet Mondrian'),
    ('TXT_KEY_GREAT_PERSON_A__197', 'Stanislaw Ignacy Witkiewicz'),
    ('TXT_KEY_GREAT_PERSON_A__200', 'Tarsila do Amaral'),
    ('TXT_KEY_GREAT_PERSON_A__205', 'Evelyn Dunbar'),
    ('TXT_KEY_GREAT_PERSON_A__207', 'Milan Konjovic'),
    ('TXT_KEY_GREAT_PERSON_A__210', 'Nguyen Nam Son'),
    ('TXT_KEY_GREAT_PERSON_A__215', 'Gao Jianfu'),
    ('TXT_KEY_GREAT_PERSON_A__220', 'Willem Gerard Hofker'),
    ('TXT_KEY_GREAT_PERSON_A__225', 'Montague Dawson'),
    ('TXT_KEY_GREAT_PERSON_A__230', 'Sawlaram Lakshman Haldankar'),
    ('TXT_KEY_GREAT_PERSON_A__235', 'Thomas Hart Benton'),
    ('TXT_KEY_GREAT_PERSON_A__236', 'Jasper Johns'),
    ('TXT_KEY_GREAT_PERSON_A__237', 'Zao Wou-Ki'),
    ('TXT_KEY_GREAT_PERSON_A__238', 'Betye Saar'),
    ('TXT_KEY_GREAT_PERSON_A__239', 'Andy Warhol'),
    ('TXT_KEY_GREAT_PERSON_A__240', 'Norval Morrisseau'),
    ('TXT_KEY_GREAT_PERSON_A__250', 'Uki'),
    ('TXT_KEY_GREAT_PERSON_A__260', 'Yunizar'),
    ('TXT_KEY_GREAT_PERSON_A__270', 'Mode Muntu'),
    ('TXT_KEY_GREAT_PERSON_A__280', 'Fahrelnissa Zeid'),
    ('TXT_KEY_GREAT_PERSON_A__290', 'Louisa Matthiasdottir'),
    ('TXT_KEY_GREAT_PERSON_A__295', 'Jean-Michel Basquiat'),
    ('TXT_KEY_GREAT_PERSON_A__300', 'Georges Mathieu'),
    ('TXT_KEY_GREAT_PERSON_A__310', 'Kacimi'),
    ('TXT_KEY_GREAT_PERSON_A__315', 'Alan Fearnley'),
    ('TXT_KEY_GREAT_PERSON_A__320', 'Babak Roshani Nejad'),
    ('TXT_KEY_GREAT_PERSON_A__330', 'Xue Mo'),
    ('TXT_KEY_GREAT_PERSON_A__340', 'Naza'),
    ('TXT_KEY_GREAT_PERSON_A__350', 'Mario Murua'),
    ('TXT_KEY_GREAT_PERSON_A__360', 'Syed Thajudeen'),
    ('TXT_KEY_GREAT_PERSON_A__370', 'Wang Yan Cheng'),
    ('TXT_KEY_GREAT_PERSON_A__375', 'Joseph McGurl'),
    ('TXT_KEY_GREAT_PERSON_A__380', 'Rachid Hanbali'),
    ('TXT_KEY_GREAT_PERSON_A__385', 'Mickalene Thomas'),
    ('TXT_KEY_GREAT_PERSON_A__390', 'Andre Kohn'),
    ('TXT_KEY_GREAT_PERSON_A__400', 'Jean Andrianaivo Ravelona'),
    ('TXT_KEY_GREAT_PERSON_A__420', 'Alex Pardee'),
  --
    ('TXT_KEY_GREAT_WORK_AW_010', 'Emperor Wen of Sui'),
    ('TXT_KEY_GREAT_WORK_AW_020', 'Great Goddess of Teotihuacan'),
    ('TXT_KEY_GREAT_WORK_AW_030', 'Along the River During the Qingming Festival'),
    ('TXT_KEY_GREAT_WORK_AW_040', 'Bodhisattva of Compassion'),
    ('TXT_KEY_GREAT_WORK_AW_050', 'Yi Am'),
    ('TXT_KEY_GREAT_WORK_AW_060', 'Zelfportret'),
    ('TXT_KEY_GREAT_WORK_AW_070', 'Geumgang Jeondo'),
    ('TXT_KEY_GREAT_WORK_AW_080', 'A North-East View of the House of Mr Emanuel Lousada Kingston Jamaica'),
    ('TXT_KEY_GREAT_WORK_AW_090', 'Sangchun'),
    ('TXT_KEY_GREAT_WORK_AW_092', 'Dream of Arcadia'),
    ('TXT_KEY_GREAT_WORK_AW_095', 'View of Dresden by Moonlight'),
    ('TXT_KEY_GREAT_WORK_AW_100', 'Hunt'),
    ('TXT_KEY_GREAT_WORK_AW_110', 'Stanczyk'),
    ('TXT_KEY_GREAT_WORK_AW_115', 'Indians spear fishing'),
    ('TXT_KEY_GREAT_WORK_AW_120', 'Surprise pr�s d''un pont au petit jour'),
    ('TXT_KEY_GREAT_WORK_AW_130', 'The Irritating Gentleman'),
    ('TXT_KEY_GREAT_WORK_AW_135', 'Winter Landscape'),
    ('TXT_KEY_GREAT_WORK_AW_140', 'November'),
    ('TXT_KEY_GREAT_WORK_AW_150', 'Haokah'),
    ('TXT_KEY_GREAT_WORK_AW_155', 'Fresh from the Garden '),
    ('TXT_KEY_GREAT_WORK_AW_160', 'Poppies'),
    ('TXT_KEY_GREAT_WORK_AW_170', 'Sammon puolustus'),
    ('TXT_KEY_GREAT_WORK_AW_178', 'The Forge'),
    ('TXT_KEY_GREAT_WORK_AW_180', 'Mme Kupka parmi Verticaux'),
    ('TXT_KEY_GREAT_WORK_AW_185', 'Apocalyptic Landscape'),
    ('TXT_KEY_GREAT_WORK_AW_187', 'Russian Cavalry on the Attack in East Prussia'),
    ('TXT_KEY_GREAT_WORK_AW_190', 'Charge of Rokitna'),
    ('TXT_KEY_GREAT_WORK_AW_193', 'Winter Night'),
    ('TXT_KEY_GREAT_WORK_AW_194', 'Boy with Blue Eyes'),
    ('TXT_KEY_GREAT_WORK_AW_195', 'Composition with Red, Yellow, Blue, and Black'),
    ('TXT_KEY_GREAT_WORK_AW_197', 'Portret Marii Nawrockiej'),
    ('TXT_KEY_GREAT_WORK_AW_200', 'Abaporu'),
    ('TXT_KEY_GREAT_WORK_AW_205', 'Self portrait'),
    ('TXT_KEY_GREAT_WORK_AW_207', 'Still Life'),
    ('TXT_KEY_GREAT_WORK_AW_210', 'Peasant women from Tonkin'),
    ('TXT_KEY_GREAT_WORK_AW_215', 'Solitary Temple in Autumn Mountains '),
    ('TXT_KEY_GREAT_WORK_AW_220', 'Portrait of Made Toei'),
    ('TXT_KEY_GREAT_WORK_AW_225', 'Days Of Old'),
    ('TXT_KEY_GREAT_WORK_AW_230', 'Glow of Hope'),
    ('TXT_KEY_GREAT_WORK_AW_235', 'Poker Night (from A Streetcar Named Desire)'),
    ('TXT_KEY_GREAT_WORK_AW_236', 'Target with Four Faces'),
    ('TXT_KEY_GREAT_WORK_AW_237', 'Untitled'),
    ('TXT_KEY_GREAT_WORK_AW_238', 'Anticipation'),
    ('TXT_KEY_GREAT_WORK_AW_239', 'Marilyn Diptych'),
    ('TXT_KEY_GREAT_WORK_AW_240', 'Thunderbird'),
    ('TXT_KEY_GREAT_WORK_AW_250', 'Quamrul Hassan'),
    ('TXT_KEY_GREAT_WORK_AW_260', 'Patatt ranting'),
    ('TXT_KEY_GREAT_WORK_AW_270', 'Fabian'),
    ('TXT_KEY_GREAT_WORK_AW_280', 'Femininity'),
    ('TXT_KEY_GREAT_WORK_AW_290', 'Sjalfsmynd'),
    ('TXT_KEY_GREAT_WORK_AW_295', 'Dustheads'),
    ('TXT_KEY_GREAT_WORK_AW_300', 'Depart Alarme II'),
    ('TXT_KEY_GREAT_WORK_AW_310', 'The time of storytellers'),
    ('TXT_KEY_GREAT_WORK_AW_315', 'Untitled'),
    ('TXT_KEY_GREAT_WORK_AW_320', 'No 3 from the Personae series'),
    ('TXT_KEY_GREAT_WORK_AW_330', 'Flower'),
    ('TXT_KEY_GREAT_WORK_AW_340', 'Red Macaw'),
    ('TXT_KEY_GREAT_WORK_AW_350', 'violencia rara y diosas blancas'),
    ('TXT_KEY_GREAT_WORK_AW_360', 'Springmood I'),
    ('TXT_KEY_GREAT_WORK_AW_370', 'Untitled'),
    ('TXT_KEY_GREAT_WORK_AW_375', 'Creation in Time and Space'),
    ('TXT_KEY_GREAT_WORK_AW_380', 'Asilah at Dawn'),
    ('TXT_KEY_GREAT_WORK_AW_385', 'Din, Une Tres Belle N�gresse 1'),
    ('TXT_KEY_GREAT_WORK_AW_390', 'Morning on the Beach'),
    ('TXT_KEY_GREAT_WORK_AW_400', 'Vers le Centre de l''Univers'),
    ('TXT_KEY_GREAT_WORK_AW_420', 'Ank Shus');

  INSERT INTO Language_en_US
    (Tag, Text)
  VALUES
  --
  --          G.Writers
  --
    ('TXT_KEY_GREAT_PERSON_W__010', 'Sin-Leqi-Unninni'),
    ('TXT_KEY_GREAT_PERSON_W__020', 'Sappho'),
    ('TXT_KEY_GREAT_PERSON_W__030', 'Nestor the Chronicler'),
    ('TXT_KEY_GREAT_PERSON_W__040', 'Snorri Sturluson'),
    ('TXT_KEY_GREAT_PERSON_W__050', 'Is''haq Nebura-Id'),
    ('TXT_KEY_GREAT_PERSON_W__060', '�igi Qutuqu'),
    ('TXT_KEY_GREAT_PERSON_W__070', 'Margery Kempe'),
    ('TXT_KEY_GREAT_PERSON_W__090', 'Miyamoto Musashi'),
    ('TXT_KEY_GREAT_PERSON_W__100', 'Hanna Diyab'),
    ('TXT_KEY_GREAT_PERSON_W__110', 'Christine de Pizan'),
    ('TXT_KEY_GREAT_PERSON_W__120', 'Margaret Cavendish'),
    ('TXT_KEY_GREAT_PERSON_W__130', 'Wu Cheng''en'),
    ('TXT_KEY_GREAT_PERSON_W__140', 'Beatrix Potter'),
    ('TXT_KEY_GREAT_PERSON_W__150', 'John Keats'),
    ('TXT_KEY_GREAT_PERSON_W__160', 'Hans Christian Andersen'),
    ('TXT_KEY_GREAT_PERSON_W__170', 'Khurdishbanu Natavan'),
    ('TXT_KEY_GREAT_PERSON_W__190', 'Howard Philips Lovecraft'),
    ('TXT_KEY_GREAT_PERSON_W__200', 'J.R.R. Tolkein'),
    ('TXT_KEY_GREAT_PERSON_W__210', 'Lucy Maud Montgomery'),
    ('TXT_KEY_GREAT_PERSON_W__220', 'Ren� Goscinny and Albert Uderzo'),
    ('TXT_KEY_GREAT_PERSON_W__230', 'Stanislaw Lem'),
    ('TXT_KEY_GREAT_PERSON_W__240', 'Leopold Sedar Senghor'),
    ('TXT_KEY_GREAT_PERSON_W__250', 'Vasily Grossman'),
    ('TXT_KEY_GREAT_PERSON_W__260', 'Witi Ihimaera'),
    ('TXT_KEY_GREAT_PERSON_W__270', 'Isaac Asimov'),
    ('TXT_KEY_GREAT_PERSON_W__280', 'Chinua Achebe'),
    ('TXT_KEY_GREAT_PERSON_W__290', 'Sylvia Plath'),
    ('TXT_KEY_GREAT_PERSON_W__300', 'Toni Morrison'),
    ('TXT_KEY_GREAT_PERSON_W__310', 'Andrzej Sapkowski'),
    ('TXT_KEY_GREAT_PERSON_W__320', 'J.K. Rowling'),
    ('TXT_KEY_GREAT_PERSON_W__330', 'Margaret Atwood'),
    ('TXT_KEY_GREAT_PERSON_W__340', 'Arundhati Roy'),
    ('TXT_KEY_GREAT_PERSON_W__350', 'Eden Robinson'),
    ('TXT_KEY_GREAT_PERSON_W__360', 'Fran�ois Cheng (Ch�ng B�oyi)'),
  --	
    ('TXT_KEY_GREAT_WORK_WW_010', 'Epic of Gilgamesh'),
    ('TXT_KEY_GREAT_WORK_WW_020', 'Ode to Aphrodite'),
    ('TXT_KEY_GREAT_WORK_WW_030', 'Tale of Bygone Years'),
    ('TXT_KEY_GREAT_WORK_WW_040', 'The Prose Edda'),
    ('TXT_KEY_GREAT_WORK_WW_050', 'Kebra Nagast (Books of Kings)'),
    ('TXT_KEY_GREAT_WORK_WW_060', 'The Secret History of the Mongols'),
    ('TXT_KEY_GREAT_WORK_WW_070', 'The Book of Margery Kemp'),
    ('TXT_KEY_GREAT_WORK_WW_090', 'Go Rin no Sho (The Book of Five Rings)'),
    ('TXT_KEY_GREAT_WORK_WW_100', 'Aladdin''s Wonderful Lamp'),
    ('TXT_KEY_GREAT_WORK_WW_110', 'The Book of the City of Ladies'),
    ('TXT_KEY_GREAT_WORK_WW_120', 'The Blazing World'),
    ('TXT_KEY_GREAT_WORK_WW_130', 'Xi Y�u J� (Journey to the West)'),
    ('TXT_KEY_GREAT_WORK_WW_140', 'The Tale of Peter Rabbit'),
    ('TXT_KEY_GREAT_WORK_WW_150', 'Ode to a Nightingale'),
    ('TXT_KEY_GREAT_WORK_WW_160', 'The Snow Queen'),
    ('TXT_KEY_GREAT_WORK_WW_170', 'Lilac'),
    ('TXT_KEY_GREAT_WORK_WW_190', 'The Call of Cthulhu'),
    ('TXT_KEY_GREAT_WORK_WW_200', 'The Hobbit'),
    ('TXT_KEY_GREAT_WORK_WW_210', 'Anne of Green Gables'),
    ('TXT_KEY_GREAT_WORK_WW_220', 'Ast�rix chez les Bretons (Asterix in Britain)'),
    ('TXT_KEY_GREAT_WORK_WW_230', 'Solaris'),
    ('TXT_KEY_GREAT_WORK_WW_240', 'Nocturnes'),
    ('TXT_KEY_GREAT_WORK_WW_250', 'Life and Fate'),
    ('TXT_KEY_GREAT_WORK_WW_260', 'Pounamu, Pounamu'),
    ('TXT_KEY_GREAT_WORK_WW_270', 'Runaround'),
    ('TXT_KEY_GREAT_WORK_WW_280', 'Things Fall Apart'),
    ('TXT_KEY_GREAT_WORK_WW_290', 'Mushrooms'),
    ('TXT_KEY_GREAT_WORK_WW_300', 'Song of Solomon'),
    ('TXT_KEY_GREAT_WORK_WW_310', 'Wiedzmin (The Witcher)'),
    ('TXT_KEY_GREAT_WORK_WW_320', 'Harry Potter and the Philosopher''s Stone'),
    ('TXT_KEY_GREAT_WORK_WW_330', 'The Handmaid''s Tale'),
    ('TXT_KEY_GREAT_WORK_WW_340', 'The God of Small Things'),
    ('TXT_KEY_GREAT_WORK_WW_350', 'Monkey Beach'),
    ('TXT_KEY_GREAT_WORK_WW_360', 'La vraie gloire est ici (Genuine glory is here)'),
  --	
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_010', 'Even the gods took fright at the Deluge,[NEWLINE]they left and went up to the heaven of Anu,[NEWLINE]lying like dogs curled up in the open.[NEWLINE]The goddess cried out like a woman in childbirth,[NEWLINE]Belet-ili wailed, whose voice is so sweet:[NEWLINE]''It is I who give birth, these people are mine![NEWLINE]And now, like fish, they fill the ocean!'''),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_020', 'Aphrodite, subtle of soul and deathless,[NEWLINE]Daughter of God, weaver of wiles, I pray thee[NEWLINE]Neither with care, dread Mistress, nor with anguish,[NEWLINE]Slay thou my spirit!'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_030', 'As long as love reign between you, God will be with you, will make your enemies submit, and you will live in peace. But if you live in hatred, strife and divisions, you will perish; you will lose the lands of your fathers and ancestors, which they acquired with much suffering. So live in peace and understanding, listen to one another.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_040', 'Of Ymer''s flesh[NEWLINE]The earth was made,[NEWLINE]And of his sweat the seas;[NEWLINE]Rocks of his bones,[NEWLINE]Trees of his hair,[NEWLINE]And the sky of his skull;[NEWLINE]But of his eyebrows[NEWLINE]The blithe powers[NEWLINE]Made Midgard for the sons of men.[NEWLINE]Of his brains[NEWLINE]All the melancholy[NEWLINE]Clouds were made.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_050', 'He who heaps up gold and silver does so to no profit without wisdom; but he who heaps up wisdom, no man can snatch it from his heart.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_060', 'At the beginning there was a blue-grey wolf, born with his destiny ordained by Heaven Above. His wife was a fallow doe. They came crossing the Tenggis. After they had settled at the source of the Onan River on Mount Burqan Qaldun, Bataciqan was born to them.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_070', 'She many times met with men of that district who said to her, ''woman, give up this life that you lead and go and spin, and card wool, as other women do, and do not suffer so much shame and so much unhappiness. We would not suffer so much for any money on earth'''),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_080', 'Evil and good meet with their due reward. Good fortune and ill luck walk side by side. But he who never walks the wrong path, need have no fear when comes the summons in the night'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_090', 'You will come to think of things in a wide sense, and taking the void as the Way, you will see the Way as void. In the void is virtue, and no evil. Wisdom has existence, principle has existence, the Way has existence, spirit is nothingness.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_100', 'In this action of joining his hands, he happened, without at all thinking of it, to rub the ring which the African magician had put upon his finger, and of the virtue of which he was as yet ignorant. Upon its being thus rubbed, a Genie of a most enormous figure and most horrid countenance, instantly rose, as it were, out of the earth before him'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_110', 'The man or the woman in whom resides greater virtue is the higher; neither the loftiness nor the lowliness of a person lies in the body according to the sex, but in the perfection of conduct and virtues.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_120', 'If you will but direct me, said the Duchess to the Spirits, which World is easiest to be conquered, her Majesty will assist me with Means, and I will trust to Fate and Fortune; for I had rather die in the adventure of noble achievements, then live in obscure and sluggish security; since by the one, I may live in a glorious Fame; and by the other I am buried in oblivion.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_130', 'One wish born in the heart of man[NEWLINE]Is known throughout Heaven and Earth.[NEWLINE]If vice or virtue lacks reward,[NEWLINE]Unjust must be the universe.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_140', 'Flopsy, Mopsy, and Cottontail - who were good little bunnies - went down the lane to gather blackberries, but Peter - who was very naughty - ran straight away to Mr. McGregor''s garden and squeezed under the gate.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_150', 'Thou wast not born for death, immortal Bird![NEWLINE]No hungry generations tread thee down;[NEWLINE]The voice I hear this passing night was heard[NEWLINE]In ancient days by emperor and clown.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_160', 'Strength lies in her heart, because she is such a sweet, innocent child. If she herself cannot reach the Snow Queen and rid little Kay of those pieces of glass, then there''s no help that we can give her.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_170', 'O poppy-cheeked, was it a skilful gardener drew you?[NEWLINE]In this flowerbed world there were all too many plain faces;[NEWLINE]Was that the reason why the almighty keeper drew you?[NEWLINE]The flowers take their colours and fragrance from you.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_190', 'Ph''nglui mglw''nafh Cthulhu R''lyeh wgah''nagl fhtagn.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_200', 'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: It was a hobbit-hole, and that means comfort.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_210', 'I''m so glad I live in a world where there are Octobers. It would be terrible if we just skipped from September to November, wouldn''t it? Look at these maple branches. Don''t they give you a thrill�several thrills? I''m going to decorate my room with them. ''Messy things'', said Marilla, whose aesthetic sense was not noticeably developed.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_220', 'You''re not too strong.[NEWLINE]- We need a strong guy only who?[NEWLINE]- Who can carry a whole barrel of magic potion.[NEWLINE]- Like somebody who fell into the potion when he was just a little baby![NEWLINE]- Ah? Oh, me![NEWLINE]- Ahaha[NEWLINE]- Let''s smash the Romans, let''s smash the Romans, let''s smash the Romans!'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_230', 'So... you think it''s the ocean? That the ocean is responsible for it all? But why? I''m not asking how, I''m simply asking why? Do you seriously think that it wants to toy with us - a sort of elementary demonomania? A planet dominated by a huge devil, who satisfies the demands of his satanic humour by sending succubi to haunt the members of a scientific expedition...? Snow, you can''t believe anything so absurd!"[NEWLINE]He muttered under his breath.[NEWLINE]"The devil isn''t such a fool as all of that...'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_240', 'The splendor of honors is like a Sahara,[NEWLINE]A huge void without dune or stony plateau without grasses, without flutter of eyelid, without thump of the heart'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_250', 'Human history is not the battle of good struggling to overcome evil. It is a battle fought by a great evil, struggling to crush a small kernel of human kindness. But if what is human in human beings has not been destroyed even now, then evil will never conquer.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_260', 'This room was the whanau; the whanau was this room. If ever you wanted to know the whanau''s accomplishments, here were  all the sports trophies, shields, photographs of the old people who''d died long ago, whakapapa or genealogy sheets, carved feather boxes, panels, figures, feather cloaks, piupius - all spilling a riot of colour and shadow throughout the sunlit room.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_270', 'The Three Laws of Robotics:[NEWLINE]1 : A robot may not injure a human being or, through inaction, allow a human being to come to harm;[NEWLINE]2 : A robot must obey the orders given it by human beings except where such orders would conflict with the First Law;[NEWLINE]3 : A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_280', 'A man who calls his kinsmen to a feast does not do so to save them from starving. They all have food in their own homes. When we gather together in the moonlit village ground it is not because of the moon. Every man can see it in his own compound. We come together because it is good for kinsmen to do so.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_290', 'We Diet on water[NEWLINE]On crumbs of shadow[NEWLINE]Bland-mannered, asking[NEWLINE]Little or nothing[NEWLINE]So many of us!'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_300', 'Perhaps that''s what all human relationships boil down to: Would you save my life? or would you take it?'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_310', '''Evil is evil, Stregobor,'' said the witcher seriously as he got up. ''Lesser, greater, middling, it''s all the same. Proportions are negotiated, boundaries blurred. I''m not a pious hermit. I haven''t done only good in my life. But if I''m to choose between one evil and another, then I prefer not to choose at all.'''),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_320', 'What happened down in the dungeons between you and Professor Quirrell is a complete secret, so, naturally the whole school knows.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_330', 'But remember that forgiveness too is a power. To beg for it is a power, and to withhold or bestow it is a power, perhaps the greatest.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_340', 'When you hurt people they begin to love you less. That''s what careless words do, they make people love you a little less.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_350', 'Names have power. This is the fundamental principle of magic everywhere. Call out the name of a supernatural being, and you will have its instant and undivided attention in the same way that your lost toddler will have yours the second it calls your name.'),
    ('TXT_KEY_GREAT_WORK_QUOTE_WQ_360', 'Thirst and hunger,[NEWLINE]Laughs and tears,[NEWLINE]Sweetness, injuries,[NEWLINE]Fury, regrets,[NEWLINE]We will discard none,[NEWLINE]We will carry them all,[NEWLINE]Everlasting viatica,[NEWLINE]For a long journey.');

  INSERT INTO Language_en_US
    (Tag, Text)
  VALUES
  --
  --          G.Generals
  --
    ('TXT_KEY_GREAT_PERSON_G__010', 'Cyrus the Great'),
    ('TXT_KEY_GREAT_PERSON_G__015', 'Dumnorix'),
    ('TXT_KEY_GREAT_PERSON_G__020', 'Trung Vuong'),
    ('TXT_KEY_GREAT_PERSON_G__030', 'Kanishka I'),
    ('TXT_KEY_GREAT_PERSON_G__040', 'Lady Trieu'),
    ('TXT_KEY_GREAT_PERSON_G__050', 'Ran Min'),
    ('TXT_KEY_GREAT_PERSON_G__055', 'Balamber'),
    ('TXT_KEY_GREAT_PERSON_G__060', 'Sarvar�jochheda'),
    ('TXT_KEY_GREAT_PERSON_G__070', 'Gwanggaeto the Great'),
    ('TXT_KEY_GREAT_PERSON_G__075', 'Narses'),
    ('TXT_KEY_GREAT_PERSON_G__080', 'Belisarius'),
    ('TXT_KEY_GREAT_PERSON_G__085', 'Abou Bakr As-Siddiq'),
    ('TXT_KEY_GREAT_PERSON_G__087', 'Heraclius'),
    ('TXT_KEY_GREAT_PERSON_G__090', 'Maya Queen Lady K''abel'),
    ('TXT_KEY_GREAT_PERSON_G__100', 'Nikephoros II Phokas'),
    ('TXT_KEY_GREAT_PERSON_G__110', 'John I Tzimiskes'),
    ('TXT_KEY_GREAT_PERSON_G__120', 'Mahmud of Ghazni'),
    ('TXT_KEY_GREAT_PERSON_G__130', 'Robert Guiscard'),
    ('TXT_KEY_GREAT_PERSON_G__140', 'Alp Arslan'),
    ('TXT_KEY_GREAT_PERSON_G__150', 'David IV of Georgia'),
    ('TXT_KEY_GREAT_PERSON_G__160', 'Saladin'),
    ('TXT_KEY_GREAT_PERSON_G__170', 'Sundiata'),
    ('TXT_KEY_GREAT_PERSON_G__175', 'Baibars'),
    ('TXT_KEY_GREAT_PERSON_G__180', 'Tran Hung Dao'),
    ('TXT_KEY_GREAT_PERSON_G__190', 'Oz Beg Khan'),
    ('TXT_KEY_GREAT_PERSON_G__195', 'Bertrand du Guesclin'),
    ('TXT_KEY_GREAT_PERSON_G__200', 'Xu Da'),
    ('TXT_KEY_GREAT_PERSON_G__210', 'Hayam Wuruk'),
    ('TXT_KEY_GREAT_PERSON_G__220', 'Jan �i�ka'),
    ('TXT_KEY_GREAT_PERSON_G__230', 'Skandenberg'),
    ('TXT_KEY_GREAT_PERSON_G__240', 'Janos Hunyadi'),
    ('TXT_KEY_GREAT_PERSON_G__250', 'Huyana Capac'),
    ('TXT_KEY_GREAT_PERSON_G__260', 'Asn�f S�g�d I'),
    ('TXT_KEY_GREAT_PERSON_G__270', 'Aminatu'),
    ('TXT_KEY_GREAT_PERSON_G__280', 'Levtraru'),
    ('TXT_KEY_GREAT_PERSON_G__290', 'Tokugawa Ieyasu'),
    ('TXT_KEY_GREAT_PERSON_G__300', 'Malik Ambar'),
    ('TXT_KEY_GREAT_PERSON_G__310', 'Queen Nanny'),
    ('TXT_KEY_GREAT_PERSON_G__320', 'Mihai Viteazu'),
    ('TXT_KEY_GREAT_PERSON_G__330', 'Nurhaci'),
    ('TXT_KEY_GREAT_PERSON_G__340', 'Jan Karol Chodkiewicz'),
    ('TXT_KEY_GREAT_PERSON_G__350', 'Nzingha Mbande'),
    ('TXT_KEY_GREAT_PERSON_G__360', 'Stanislaw Koniecpolski'),
    ('TXT_KEY_GREAT_PERSON_G__370', 'Jan Sobieski'),
    ('TXT_KEY_GREAT_PERSON_G__380', 'Shivaji Bosle'),
    ('TXT_KEY_GREAT_PERSON_G__385', 'Baji Rao I'),
    ('TXT_KEY_GREAT_PERSON_G__390', 'Ahmad Khan Abdali'),
    ('TXT_KEY_GREAT_PERSON_G__395', 'James Wolfe'),	
    ('TXT_KEY_GREAT_PERSON_G__397', 'Alexander Suvorov'),	
    ('TXT_KEY_GREAT_PERSON_G__400', 'Toussaint L�Ouverture'),
    ('TXT_KEY_GREAT_PERSON_G__410', 'Mikhail Kutuzov'),
    ('TXT_KEY_GREAT_PERSON_G__420', 'Nguyen Hue'),
    ('TXT_KEY_GREAT_PERSON_G__425', 'Jos� Gervasio Artigas'),
    ('TXT_KEY_GREAT_PERSON_G__430', 'Piotr Ivanovitch Bagration'),
    ('TXT_KEY_GREAT_PERSON_G__440', 'Ranj�t Singh'),
    ('TXT_KEY_GREAT_PERSON_G__445', 'Kazimierz Pulaski'),
    ('TXT_KEY_GREAT_PERSON_G__450', 'Simon Bolivar'),
    ('TXT_KEY_GREAT_PERSON_G__455', 'Ignacy Kruszewski'),
    ('TXT_KEY_GREAT_PERSON_G__460', 'Cochise'),
    ('TXT_KEY_GREAT_PERSON_G__465', 'Seh-Dong-Hong-Beh'),
    ('TXT_KEY_GREAT_PERSON_G__470', 'Crazy Horse'),
    ('TXT_KEY_GREAT_PERSON_G__475', 'Richard Hebden O''Grady Haly'),
    ('TXT_KEY_GREAT_PERSON_G__480', 'Kumu Eseko Elombe'),
    ('TXT_KEY_GREAT_PERSON_G__481', 'Mekonnen Welde Mikael'),
    ('TXT_KEY_GREAT_PERSON_G__482', 'John Pershing'),
    ('TXT_KEY_GREAT_PERSON_G__483', 'Sir Arthur William Currie'),
    ('TXT_KEY_GREAT_PERSON_G__485', 'Douglas MacArthur'),
    ('TXT_KEY_GREAT_PERSON_G__487', 'Edward Rydz-Smigly'),
    ('TXT_KEY_GREAT_PERSON_G__48A', 'Edward Puttick'),
    ('TXT_KEY_GREAT_PERSON_G__489', 'Kiyotake Kawaguchi'),
    ('TXT_KEY_GREAT_PERSON_G__490', 'Josip Broz Tito'),
    ('TXT_KEY_GREAT_PERSON_G__491', 'Matthew Bunker Ridgway'),
    ('TXT_KEY_GREAT_PERSON_G__492', 'Lewis Burwell'),
    ('TXT_KEY_GREAT_PERSON_G__49A', 'Simon Spoor'),
    ('TXT_KEY_GREAT_PERSON_G__49C', 'Philippe Leclerc'),
    ('TXT_KEY_GREAT_PERSON_G__493', 'Juan Jos� Valle'),
    ('TXT_KEY_GREAT_PERSON_G__494', 'Vo Nguyen Giap'),
    ('TXT_KEY_GREAT_PERSON_G__495', 'Moshe Dayan'),
    ('TXT_KEY_GREAT_PERSON_G__49B', 'Marcel Bigeard'),
    ('TXT_KEY_GREAT_PERSON_G__496', 'Chung Il-kwon'),
    ('TXT_KEY_GREAT_PERSON_G__497', 'Hal Moore'),
    ('TXT_KEY_GREAT_PERSON_G__498', 'Mario Men�ndez'),
    ('TXT_KEY_GREAT_PERSON_G__500', 'Norman Schwarzkopf'),
    ('TXT_KEY_GREAT_PERSON_G__505', 'Liamine Z�roual'),
    ('TXT_KEY_GREAT_PERSON_G__506', 'Jehangir Karamat'),
    ('TXT_KEY_GREAT_PERSON_G__50A', 'Fernando Tapias Stahelin'),
    ('TXT_KEY_GREAT_PERSON_G__507', 'Abdul Fatah Younis'),
    ('TXT_KEY_GREAT_PERSON_G__510', 'David Petraeus'),
    ('TXT_KEY_GREAT_PERSON_G__515', 'Yasar G�ler'),
    ('TXT_KEY_GREAT_PERSON_G__520', 'C�sar Astudillo Salcedo'),
    ('TXT_KEY_GREAT_PERSON_G__530', 'Vladimer Chachibaia'),
    ('TXT_KEY_GREAT_PERSON_G__540', 'Melvyn Ong'),
  --
  --          G.Admirals
  --	
    ('TXT_KEY_GREAT_PERSON_B__010', 'Hannu'),
    ('TXT_KEY_GREAT_PERSON_B__020', 'Pytheas'),
    ('TXT_KEY_GREAT_PERSON_B__030', 'Xu Fu'),
    ('TXT_KEY_GREAT_PERSON_B__040', 'Zhang Quian'),
    ('TXT_KEY_GREAT_PERSON_B__045', 'Lacedaimonius'),
    ('TXT_KEY_GREAT_PERSON_B__047', 'Himerios'),
    ('TXT_KEY_GREAT_PERSON_B__050', 'Ng� Quyen'),
    ('TXT_KEY_GREAT_PERSON_B__060', 'George of Antioch'),
    ('TXT_KEY_GREAT_PERSON_B__063', 'Lamba Doria'),
    ('TXT_KEY_GREAT_PERSON_B__065', 'Hugues Quieret'),
    ('TXT_KEY_GREAT_PERSON_B__067', 'Jeanne de Belleville'),
    ('TXT_KEY_GREAT_PERSON_B__070', 'Wang Dayuan'),
    ('TXT_KEY_GREAT_PERSON_B__072', 'Hamza Bey'),
    ('TXT_KEY_GREAT_PERSON_B__073', 'Vincenzo Cappello'),
    ('TXT_KEY_GREAT_PERSON_B__074', 'Juan Martinez de Recalde'),
    ('TXT_KEY_GREAT_PERSON_B__075', 'Yi Sun-sin'),
    ('TXT_KEY_GREAT_PERSON_B__080', 'Keumalahayati'),
    ('TXT_KEY_GREAT_PERSON_B__085', 'Martim Afonso de Castro'),
    ('TXT_KEY_GREAT_PERSON_B__090', 'Gustav Horn'),
    ('TXT_KEY_GREAT_PERSON_B__100', 'Cornelis Tromp'),
    ('TXT_KEY_GREAT_PERSON_B__103', 'Jan van Brakel'),
    ('TXT_KEY_GREAT_PERSON_B__104', 'Jean Bart'),
    ('TXT_KEY_GREAT_PERSON_B__105', 'Fiodor Apraxine'),
    ('TXT_KEY_GREAT_PERSON_B__107', 'George Byng'),
    ('TXT_KEY_GREAT_PERSON_B__110', 'Kanhoji Angre'),
    ('TXT_KEY_GREAT_PERSON_B__120', 'Peter Tordenskjold'),
    ('TXT_KEY_GREAT_PERSON_B__128', 'Robert Surcouf'),
    ('TXT_KEY_GREAT_PERSON_B__130', 'Ching Shih'),
    ('TXT_KEY_GREAT_PERSON_B__135', 'Steen Andersen Bille'),
    ('TXT_KEY_GREAT_PERSON_B__150', 'Miguel Grau Seminario'),
    ('TXT_KEY_GREAT_PERSON_B__160', 'Hans von Koester'),
    ('TXT_KEY_GREAT_PERSON_B__170', 'August von Thomsen'),
    ('TXT_KEY_GREAT_PERSON_B__172', 'Abraham George Ellis'),
    ('TXT_KEY_GREAT_PERSON_B__175', 'Anton Haus'),
    ('TXT_KEY_GREAT_PERSON_B__180', 'Ijuin Goro'),
    ('TXT_KEY_GREAT_PERSON_B__190', 'Paolo Thaon'),
    ('TXT_KEY_GREAT_PERSON_B__195', 'Sir William Clarkson'),
    ('TXT_KEY_GREAT_PERSON_B__200', 'J�zef Unrug'),
    ('TXT_KEY_GREAT_PERSON_B__205', 'Mineichi Koga'),
    ('TXT_KEY_GREAT_PERSON_B__203', 'Frank Jack Fletcher'),
    ('TXT_KEY_GREAT_PERSON_B__206', 'Conrad Helfrich'),
    ('TXT_KEY_GREAT_PERSON_B__210', 'Vladimir Kasatonov'),
    ('TXT_KEY_GREAT_PERSON_B__212', 'Ram Dass Katari'),
    ('TXT_KEY_GREAT_PERSON_B__215', 'Bengt Lundvall'),
    ('TXT_KEY_GREAT_PERSON_B__220', 'Jerzy Tumaniszwili'),
    ('TXT_KEY_GREAT_PERSON_B__230', 'Sveto Letica'),
    ('TXT_KEY_GREAT_PERSON_B__235', 'Theodoros Degiannis'),
    ('TXT_KEY_GREAT_PERSON_B__240', 'L�m Nguon T�nh'),
    ('TXT_KEY_GREAT_PERSON_B__245', 'P�vlos Koundouri�tis'),
    ('TXT_KEY_GREAT_PERSON_B__250', 'Konstantin Makarov'),
    ('TXT_KEY_GREAT_PERSON_B__251', 'Jan Klenberg'),
    ('TXT_KEY_GREAT_PERSON_B__252', 'Gulab Mohanlal Hiranandani'),
    ('TXT_KEY_GREAT_PERSON_B__270', 'Lillian Elaine Fishburne'),
    ('TXT_KEY_GREAT_PERSON_B__300', 'Wasantha Karannagoda'),
    ('TXT_KEY_GREAT_PERSON_B__325', '�douard Guillaud'),
    ('TXT_KEY_GREAT_PERSON_B__350', 'Ahmed Khaled'),
    ('TXT_KEY_GREAT_PERSON_B__355', 'Lee Hsi-ming'),
    ('TXT_KEY_GREAT_PERSON_B__357', 'Alireza Tangsiri'),
    ('TXT_KEY_GREAT_PERSON_B__360', 'Louise Kathrine Dedichen'),
    ('TXT_KEY_GREAT_PERSON_B__370', 'Bob Auchterlonie'),
    ('TXT_KEY_GREAT_PERSON_B__390', 'Gladys Mbulaheni'),
  --
  --          G.Merchants
  --
    ('TXT_KEY_GREAT_PERSON_N__002', 'Colaeus'),
    ('TXT_KEY_GREAT_PERSON_N__004', 'Marcus Licinius Crassus'),
    ('TXT_KEY_GREAT_PERSON_N__010', 'Tunka Manin'),
    ('TXT_KEY_GREAT_PERSON_N__020', 'al-Mustansir'),
    ('TXT_KEY_GREAT_PERSON_N__030', 'Suryavarman'),
    ('TXT_KEY_GREAT_PERSON_N__035', 'Marco Polo'),
    ('TXT_KEY_GREAT_PERSON_N__040', 'Musa of Mali'),
    ('TXT_KEY_GREAT_PERSON_N__050', 'Ibn Khaldoun'),
    ('TXT_KEY_GREAT_PERSON_N__060', 'Cosimo de Medici'),
    ('TXT_KEY_GREAT_PERSON_N__070', 'Nyatsimba-Mutota'),
    ('TXT_KEY_GREAT_PERSON_N__075', 'Jacob Fugger'),
    ('TXT_KEY_GREAT_PERSON_N__077', 'Konstanty Korniakt'),
    ('TXT_KEY_GREAT_PERSON_N__080', 'Thomas Gresham'),
    ('TXT_KEY_GREAT_PERSON_N__090', 'Shah Abbas'),
    ('TXT_KEY_GREAT_PERSON_N__100', 'Tanaka Shosuke'),
    ('TXT_KEY_GREAT_PERSON_N__105', 'Piero de'' Bardi'),
    ('TXT_KEY_GREAT_PERSON_N__110', 'Osei Tutu'),
    ('TXT_KEY_GREAT_PERSON_N__115', 'Sava Tekelija'),
    ('TXT_KEY_GREAT_PERSON_N__120', 'Howqua'),
    ('TXT_KEY_GREAT_PERSON_N__130', 'Nathan Rotschild'),
    ('TXT_KEY_GREAT_PERSON_N__140', 'Adrian van der Hoop'),
    ('TXT_KEY_GREAT_PERSON_N__145', 'Heinrich Nestle'),
    ('TXT_KEY_GREAT_PERSON_N__150', 'Tippu Tip'),
    ('TXT_KEY_GREAT_PERSON_N__155', 'Jamsetji Nusserwanji Tata'),
    ('TXT_KEY_GREAT_PERSON_N__160', 'Rumaliza'),
    ('TXT_KEY_GREAT_PERSON_N__170', 'Cecil Rhodes'),
    ('TXT_KEY_GREAT_PERSON_N__180', 'Simon Iturri Patino'),
    ('TXT_KEY_GREAT_PERSON_N__185', 'John Jacob Astor IV'),
    ('TXT_KEY_GREAT_PERSON_N__187', 'Madam C.J. Walker'),
    ('TXT_KEY_GREAT_PERSON_N__188', 'Helena Rubinstein'),
    ('TXT_KEY_GREAT_PERSON_N__18A', 'Tom� de Barros Queir�s'),
    ('TXT_KEY_GREAT_PERSON_N__189', 'Melitta Bentz'),
    ('TXT_KEY_GREAT_PERSON_N__18B', 'Fran�ois Blais'),
    ('TXT_KEY_GREAT_PERSON_N__190', 'Osman Ali Khan'),
    ('TXT_KEY_GREAT_PERSON_N__195', 'David Sarnoff'),
    ('TXT_KEY_GREAT_PERSON_N__197', 'Raymond Rubicam'),
    ('TXT_KEY_GREAT_PERSON_N__200', 'T.V.Soong'),
    ('TXT_KEY_GREAT_PERSON_N__210', 'Yoyoda Tatsugoro'),
    ('TXT_KEY_GREAT_PERSON_N__215', 'Est�e Lauder'),
    ('TXT_KEY_GREAT_PERSON_N__217', 'Masaru Ibuka'),
    ('TXT_KEY_GREAT_PERSON_N__219', 'David Ogilvy'),
    ('TXT_KEY_GREAT_PERSON_N__220', 'Taiichi Ohno'),
    ('TXT_KEY_GREAT_PERSON_N__225', 'Sam Walton'),
    ('TXT_KEY_GREAT_PERSON_N__227', 'Karl Albrecht'),
    ('TXT_KEY_GREAT_PERSON_N__230', 'Ingvar Kamprad'),
    ('TXT_KEY_GREAT_PERSON_N__240', 'Li Ka-Shing'),
    ('TXT_KEY_GREAT_PERSON_N__242', 'Lee Shau-kee'),
    ('TXT_KEY_GREAT_PERSON_N__245', 'Carl Icahn'),
    ('TXT_KEY_GREAT_PERSON_N__250', 'Carlos Slim'),
    ('TXT_KEY_GREAT_PERSON_N__260', 'Muhammad Yunus'),
    ('TXT_KEY_GREAT_PERSON_N__270', 'Haji Bolkiah'),
    ('TXT_KEY_GREAT_PERSON_N__280', 'Scrooge McDuck'),
    ('TXT_KEY_GREAT_PERSON_N__285', 'Bernard Arnault'),
    ('TXT_KEY_GREAT_PERSON_N__290', 'Mukesh Ambani'),
    ('TXT_KEY_GREAT_PERSON_N__292', 'Aliko Dangote'),
    ('TXT_KEY_GREAT_PERSON_N__293', 'Masayoshi Son'),
    ('TXT_KEY_GREAT_PERSON_N__295', 'Jeff Bezos'),
    ('TXT_KEY_GREAT_PERSON_N__297', 'Jack Ma'),
    ('TXT_KEY_GREAT_PERSON_N__298', 'Michael Dell'),
    ('TXT_KEY_GREAT_PERSON_N__300', 'Jerry Jang'),
    ('TXT_KEY_GREAT_PERSON_N__400', 'Colin Huang Zheng');

  INSERT INTO Language_en_US
    (Tag, Text)
  VALUES
  --
  --          G.Engineers
  --
    ('TXT_KEY_GREAT_PERSON_E__010', 'Tapputi'),
    ('TXT_KEY_GREAT_PERSON_E__015', 'Eupalinos'),
    ('TXT_KEY_GREAT_PERSON_E__020', 'Ximen Bao'),
    ('TXT_KEY_GREAT_PERSON_E__023', 'Marcus Vitruvius Pollio'),
    ('TXT_KEY_GREAT_PERSON_E__024', 'Apollodorus of Damascus'),
    ('TXT_KEY_GREAT_PERSON_E__025', 'Isidore of Miletus'),
    ('TXT_KEY_GREAT_PERSON_E__030', 'Anthemius of Tralles'),
    ('TXT_KEY_GREAT_PERSON_E__040', 'Al-Ishafani'),
    ('TXT_KEY_GREAT_PERSON_E__050', 'Yu Hao'),
    ('TXT_KEY_GREAT_PERSON_E__060', 'Maslama am-Majriti'),
    ('TXT_KEY_GREAT_PERSON_E__070', 'Su Song'),
    ('TXT_KEY_GREAT_PERSON_E__075', 'Shen Kuo'),
    ('TXT_KEY_GREAT_PERSON_E__080', 'Al-Jazari'),
    ('TXT_KEY_GREAT_PERSON_E__090', 'Senenmut'),
    ('TXT_KEY_GREAT_PERSON_E__100', 'Mimar Sinan'),
    ('TXT_KEY_GREAT_PERSON_E__110', 'Gunadharma'),
    ('TXT_KEY_GREAT_PERSON_E__115', 'Juanelo Turriano'),
    ('TXT_KEY_GREAT_PERSON_E__120', 'Taqi al-Din'),
    ('TXT_KEY_GREAT_PERSON_E__130', 'Koca Kasim Aga'),
    ('TXT_KEY_GREAT_PERSON_E__131', 'Giovanni Branca'),
    ('TXT_KEY_GREAT_PERSON_E__133', 'John Smeaton'),
    ('TXT_KEY_GREAT_PERSON_E__135', 'John Spilsbury'),
    ('TXT_KEY_GREAT_PERSON_E__140', 'Krikor Balyan'),
    ('TXT_KEY_GREAT_PERSON_E__144', 'George Stephenson'),
    ('TXT_KEY_GREAT_PERSON_E__142', 'Richard Trevithick'),
    ('TXT_KEY_GREAT_PERSON_E__145', 'Charles Babbage'),
    ('TXT_KEY_GREAT_PERSON_E__14C', 'Jacques Triger'),
    ('TXT_KEY_GREAT_PERSON_E__14A', 'Joseph Whitworth'),
    ('TXT_KEY_GREAT_PERSON_E__14D', 'Sandford Fleming'),
    ('TXT_KEY_GREAT_PERSON_E__146', 'Gottlieb Daimler'),
    ('TXT_KEY_GREAT_PERSON_E__14E', 'Elijah McCoy'),
    ('TXT_KEY_GREAT_PERSON_E__14F', 'Nikola� Joukovski'),
    ('TXT_KEY_GREAT_PERSON_E__147', 'Visvesvaraya'),
    ('TXT_KEY_GREAT_PERSON_E__148', 'Henry Ford'),
    ('TXT_KEY_GREAT_PERSON_E__149', 'Lee De Forest'),
    ('TXT_KEY_GREAT_PERSON_E__14G', 'Pedro Paulet'),
    ('TXT_KEY_GREAT_PERSON_E__14H', 'Stephen Timoshenko'),
    ('TXT_KEY_GREAT_PERSON_E__14I', 'Ryoichi Yazu'),
    ('TXT_KEY_GREAT_PERSON_E__14B', 'Barnes Wallis'),
    ('TXT_KEY_GREAT_PERSON_E__150', 'K�lm�n Tihanyi'),
    ('TXT_KEY_GREAT_PERSON_E__153', 'Tommy Flowers'),
    ('TXT_KEY_GREAT_PERSON_E__154', 'Sergue� Korolev'),
    ('TXT_KEY_GREAT_PERSON_E__15A', 'Soichiro Honda'),
    ('TXT_KEY_GREAT_PERSON_E__15C', 'Oleg Antonov'),
    ('TXT_KEY_GREAT_PERSON_E__15B', 'Pierre B�zier'),
    ('TXT_KEY_GREAT_PERSON_E__155', 'Hedy Lamarr'),
    ('TXT_KEY_GREAT_PERSON_E__160', 'Ilya Prigogine'),
    ('TXT_KEY_GREAT_PERSON_E__170', 'Muzharul Islam'),
    ('TXT_KEY_GREAT_PERSON_E__175', 'Jack Kilby'),
    ('TXT_KEY_GREAT_PERSON_E__177', 'Giulio Alfieri'),
    ('TXT_KEY_GREAT_PERSON_E__180', 'Abdus Salam'),
    ('TXT_KEY_GREAT_PERSON_E__182', 'Jacek Karpinski'),
    ('TXT_KEY_GREAT_PERSON_E__185', 'Fazlur Khan'),
    ('TXT_KEY_GREAT_PERSON_E__186', 'James West'),
    ('TXT_KEY_GREAT_PERSON_E__190', 'Patricia Bath'),
    ('TXT_KEY_GREAT_PERSON_E__195', 'Burt Rutan'),
    ('TXT_KEY_GREAT_PERSON_E__200', 'Ken Yeang'),
    ('TXT_KEY_GREAT_PERSON_E__205', 'Steve Wozniak'),
    ('TXT_KEY_GREAT_PERSON_E__210', 'Carlos paz de Araujo'),
    ('TXT_KEY_GREAT_PERSON_E__220', 'Reza Ghadiri'),
    ('TXT_KEY_GREAT_PERSON_E__290', 'Elon Musk'),
  --
  --          G.Scientists
  --
    ('TXT_KEY_GREAT_PERSON_S__010', 'M�ryt-Ptah'),
    ('TXT_KEY_GREAT_PERSON_S__020', 'Ahmes'),
    ('TXT_KEY_GREAT_PERSON_S__023', 'Anaximander'),
    ('TXT_KEY_GREAT_PERSON_S__025', 'Eratosthenes'),
    ('TXT_KEY_GREAT_PERSON_S__027', 'Hipparque'),
    ('TXT_KEY_GREAT_PERSON_S__030', 'Yajnavalkya'),
    ('TXT_KEY_GREAT_PERSON_S__035', 'Claudius Galenus'),
    ('TXT_KEY_GREAT_PERSON_S__040', 'Pei Xiu'),
    ('TXT_KEY_GREAT_PERSON_S__050', 'Panini'),
    ('TXT_KEY_GREAT_PERSON_S__055', 'John Philoponus'),
    ('TXT_KEY_GREAT_PERSON_S__060', 'Brahmagupta'),
    ('TXT_KEY_GREAT_PERSON_S__066', 'Thales of Miletus'),
    ('TXT_KEY_GREAT_PERSON_S__070', 'Abdallah al-Marwazi Habash al-Hasib'),
    ('TXT_KEY_GREAT_PERSON_S__080', 'Baudhayan'),
    ('TXT_KEY_GREAT_PERSON_S__090', 'Al Battani'),
    ('TXT_KEY_GREAT_PERSON_S__095', 'Abu Al-Qasim'),
    ('TXT_KEY_GREAT_PERSON_S__098', 'Ibn Sahl'),
    ('TXT_KEY_GREAT_PERSON_S__100', 'Al-Haytham'),
    ('TXT_KEY_GREAT_PERSON_S__110', 'Al-Biruni'),
    ('TXT_KEY_GREAT_PERSON_S__120', 'Omar Khayyam'),
    ('TXT_KEY_GREAT_PERSON_S__130', 'Qin Jiushao'),
    ('TXT_KEY_GREAT_PERSON_S__140', 'Qotb al-Din Chirazi'),
    ('TXT_KEY_GREAT_PERSON_S__150', 'Madhawa'),
    ('TXT_KEY_GREAT_PERSON_S__160', 'Ulugh Beg'),
    ('TXT_KEY_GREAT_PERSON_S__165', 'William Harvey'),
    ('TXT_KEY_GREAT_PERSON_S__170', 'Xu Xiake'),
    ('TXT_KEY_GREAT_PERSON_S__175', 'Robert Hooke'),
    ('TXT_KEY_GREAT_PERSON_S__180', 'Seki Takakazu'),
    ('TXT_KEY_GREAT_PERSON_S__183', 'Daniel Bernoulli'),
    ('TXT_KEY_GREAT_PERSON_S__185', '�milie du Ch�telet'),
    ('TXT_KEY_GREAT_PERSON_S__187', 'Carl von Linn�'),
    ('TXT_KEY_GREAT_PERSON_S__190', 'Juan Ignacio Molina'),
    ('TXT_KEY_GREAT_PERSON_S__195', 'Alessandro Volta'),
    ('TXT_KEY_GREAT_PERSON_S__196', 'Giovanni Battista Venturi'),
    ('TXT_KEY_GREAT_PERSON_S__200', 'Wang Zhenyi'),
    ('TXT_KEY_GREAT_PERSON_S__210', 'J�nos Bolyai'),
    ('TXT_KEY_GREAT_PERSON_S__215', 'James Young'),
    ('TXT_KEY_GREAT_PERSON_S__217', 'Ada Lovelace'),
    ('TXT_KEY_GREAT_PERSON_S__220', 'Florence Nightingale'),
    ('TXT_KEY_GREAT_PERSON_S__222', 'Gregor Mendel'),
    ('TXT_KEY_GREAT_PERSON_S__225', 'Dmitri Mendele�ev'),
    ('TXT_KEY_GREAT_PERSON_S__230', 'Sofia Vasilyevna'),
    ('TXT_KEY_GREAT_PERSON_S__231', 'Henri Becquerel'),
    ('TXT_KEY_GREAT_PERSON_S__232', 'Santiago Ram�n y Cajal'),
    ('TXT_KEY_GREAT_PERSON_S__233', 'Max Planck'),
    ('TXT_KEY_GREAT_PERSON_S__234', 'Kazimierz Funk'),
    ('TXT_KEY_GREAT_PERSON_S__235', 'Jan Czochralski'),
    ('TXT_KEY_GREAT_PERSON_S__240', 'Ramanujan'),
    ('TXT_KEY_GREAT_PERSON_S__245', 'Erwin Schr�dinger'),
    ('TXT_KEY_GREAT_PERSON_S__246', 'Edwin Hubble'),
    ('TXT_KEY_GREAT_PERSON_S__247', 'Janaki Ammal'),
    ('TXT_KEY_GREAT_PERSON_S__250', 'Stefan Banach'),
    ('TXT_KEY_GREAT_PERSON_S__260', 'Leo Szilard'),
    ('TXT_KEY_GREAT_PERSON_S__262', 'Linus Pauling'),
    ('TXT_KEY_GREAT_PERSON_S__263', 'Werner Heisenberg'),
    ('TXT_KEY_GREAT_PERSON_S__265', 'Claude L�vi-Strauss'),
    ('TXT_KEY_GREAT_PERSON_S__270', 'Chandrasekhar'),
    ('TXT_KEY_GREAT_PERSON_S__280', 'Shiing-Shen Chern'),
    ('TXT_KEY_GREAT_PERSON_S__290', 'Chieng-Shiung Wu'),
    ('TXT_KEY_GREAT_PERSON_S__295', 'Alan Turing'),
    ('TXT_KEY_GREAT_PERSON_S__296', 'Mary Leakey'),
    ('TXT_KEY_GREAT_PERSON_S__298', 'Stephanie Kwolek'),
    ('TXT_KEY_GREAT_PERSON_S__300', 'Aziz Ab''S�ber'),
    ('TXT_KEY_GREAT_PERSON_S__310', 'Zofia Kielan-Jaworowska'),
    ('TXT_KEY_GREAT_PERSON_S__312', 'Abdus Salam'),
    ('TXT_KEY_GREAT_PERSON_S__313', 'James Dewey Watson'),
    ('TXT_KEY_GREAT_PERSON_S__31A', 'Noam Chomsky'),
    ('TXT_KEY_GREAT_PERSON_S__314', 'Tu Youyou'),
    ('TXT_KEY_GREAT_PERSON_S__315', 'Carl Sagan'),
    ('TXT_KEY_GREAT_PERSON_S__316', 'Jane Goodall'),
    ('TXT_KEY_GREAT_PERSON_S__31C', 'Seiji Ogawa'),
    ('TXT_KEY_GREAT_PERSON_S__31B', 'David Baltimore'),
    ('TXT_KEY_GREAT_PERSON_S__317', 'Stephen Hawking'),
    ('TXT_KEY_GREAT_PERSON_S__320', 'Ahmed Zewail'),
    ('TXT_KEY_GREAT_PERSON_S__330', 'Shirley Jackson'),
    ('TXT_KEY_GREAT_PERSON_S__335', 'Alan Guth'),
    ('TXT_KEY_GREAT_PERSON_S__337', 'Alain Aspect'),
    ('TXT_KEY_GREAT_PERSON_S__340', 'Ahmed Zewail'),
    ('TXT_KEY_GREAT_PERSON_S__345', 'Jack Szostak'),
    ('TXT_KEY_GREAT_PERSON_S__350', 'Tim Berners-Lee'),
    ('TXT_KEY_GREAT_PERSON_S__355', 'Ashoke Sen'),
    ('TXT_KEY_GREAT_PERSON_S__360', 'Neil deGrasse Tyson'),
    ('TXT_KEY_GREAT_PERSON_S__370', 'Lene Hau');
